'use client';

import { useParams, useRouter } from 'next/navigation';
import EmailView from '@/components/emails/EmailView';
import type { Email } from '@/types';
import { Button } from '@/components/ui/button';
import { ArrowLeft, Loader2 } from 'lucide-react';
import { useEffect, useState } from 'react';

// This MOCK_EMAIL_DB serves as a fallback for direct navigation or if localStorage fails.
// For items coming from the dashboard query, localStorage will be the primary source.
const MOCK_EMAIL_DB: Record<string, Email> = {
  'mock-1': { // Example ID for initial mock, adjust if needed
    id: 'mock-1', // Keep ID consistent with key
    sender: 'Alice Wonderland (Fallback)',
    subject: 'Project Update: Caterpillar (Fallback)',
    body: 'This is fallback content for Alice. If you see this, data from localStorage might not have loaded.\n\nHi Team,\n\nJust a quick update on the Caterpillar project...',
    summary: 'Alice reports a delay in Caterpillar project phase 2 due to mushroom supply issues. Bob is seeking new suppliers. Action items: secure supply and finalize guest list.',
    timestamp: new Date('2024-07-15T10:00:00Z').getTime(),
    isRead: true,
  },
  'mock-2': {
    id: 'mock-2',
    sender: 'Bob The Builder (Fallback)',
    subject: 'Re: Construction Plans (Fallback)',
    body: 'This is fallback content for Bob. If you see this, data from localStorage might not have loaded.\n\nHey Alice,\n\nCan we fix it? Yes, we can! ...',
    summary: 'Bob confirms construction plans for the rabbit hole are good but needs clarification on looking glass material (tempered or enchanted).',
    timestamp: new Date('2024-07-15T09:30:00Z').getTime(),
    isRead: false,
  },
   'mock-initial-1': { // Ensure these IDs can be matched if needed by initial dashboard emails
    id: 'mock-initial-1',
    sender: 'Tech Conference Updates (Fallback)',
    subject: 'Call for Papers Extended! (Fallback)',
    body: 'This is fallback content. Dear Esteemed Professionals,\n\nWe are excited to announce that the deadline for paper submissions...',
    summary: 'The deadline for paper submissions for the Annual Tech Summit has been extended by two weeks. New deadline is August 15th.',
    timestamp: Date.now() - Math.floor(Math.random() * 1000000000),
    isRead: false,
  },
  // Add other mock-initial-X entries if they are generated by dashboard's initial load
  // and you want a specific fallback for them.
};


export default function EmailPage() {
  const router = useRouter();
  const params = useParams();
  const id = params.id as string;
  const [email, setEmailData] = useState<Email | null | undefined>(undefined); // undefined for loading state

  useEffect(() => {
    let emailFound = false;
    if (id && typeof window !== 'undefined') {
      const storedEmailJson = localStorage.getItem(`email-${id}`);
      if (storedEmailJson) {
        try {
          const storedEmail = JSON.parse(storedEmailJson) as Email;
          // Basic validation: check if it has an id and subject, for example
          if (storedEmail && storedEmail.id && storedEmail.subject) {
            setEmailData(storedEmail);
            emailFound = true;
          } else {
            console.warn("Stored email data for id ${id} is invalid, removing.");
            localStorage.removeItem(`email-${id}`);
          }
        } catch (e) {
          console.error("Failed to parse email from localStorage for id ${id}:", e);
          localStorage.removeItem(`email-${id}`); // Remove corrupted data
        }
      }
    }

    if (!emailFound && id) {
      // Fallback to MOCK_EMAIL_DB if not found in localStorage or if localStorage is not available
      // console.log(`Email with id ${id} not found in localStorage, trying MOCK_EMAIL_DB.`);
      setTimeout(() => { // Simulate network delay for fallback
        const fallbackEmail = MOCK_EMAIL_DB[id] || Object.values(MOCK_EMAIL_DB).find(e => e.id === id);
        if (fallbackEmail) {
          setEmailData(fallbackEmail);
        } else {
          // If still not found after checking MOCK_EMAIL_DB by key and by iterating (in case ID structure differs)
          // Try a prefix match as a last resort for old "mock-X" style IDs.
          const idPrefix = id.match(/mock-\\d+/)?.[0] || id.match(/mock-initial-\\d+/)?.[0];
          let foundByPrefix: Email | undefined = undefined;
          if (idPrefix) {
             foundByPrefix = Object.values(MOCK_EMAIL_DB).find(e => e.id.startsWith(idPrefix));
          }
          setEmailData(foundByPrefix || null); // null if not found after all fallbacks
        }
      }, 200); // Shorter delay for fallback
    } else if (!id) {
        setEmailData(null); // No ID, so no email to load
    }
    // If emailFound is true, setEmailData was already called, so no further action needed here for that case.

  }, [id]);

  if (email === undefined) {
    return (
      <div className="flex flex-col items-center justify-center h-[calc(100vh-200px)]">
        <Loader2 className="h-12 w-12 text-primary animate-spin" />
        <p className="mt-4 text-muted-foreground">Loading email content...</p>
      </div>
    );
  }

  if (!email) {
    return (
      <div className="text-center py-10">
        <h2 className="text-2xl font-semibold mb-4">Email Not Found</h2>
        <p className="text-muted-foreground mb-6">The email (ID: {id}) you are looking for does not exist or could not be loaded from localStorage or fallbacks.</p>
        <Button onClick={() => router.push('/dashboard')}>
          <ArrowLeft className="mr-2 h-4 w-4" />
          Back to Dashboard
        </Button>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <Button variant="outline" onClick={() => router.push('/dashboard')} className="mb-6">
        <ArrowLeft className="mr-2 h-4 w-4" />
        Back to Dashboard
      </Button>
      <EmailView email={email} />
    </div>
  );
}
